### ISSUE TITLE
Is there API gateway here?

### ISSUE THREAD

**Issue by Ciantic** [theiterators/reactive-microservices#10]
I'm trying to figure out best way to setup microservices and API for single-page frontend application.

Of course there are many ways to do it, but is there API gateway in this project? Your diagram: http://www.typesafe.com/activator/template/reactive-microservices/tutorial/arch.png suggests there is not a API gateway.

Do you see it as a requirement? I've found it in here: http://www.infoq.com/articles/seven-uservices-antipatterns here is the image: http://cdn.infoq.com/statics_s1_20150819-0313/resource/articles/seven-uservices-antipatterns/en/resources/fig4.jpg

Also someone has done a play + microservices template with a similar image: https://github.com/knoldus/playing-microservices of API gateway, however, I don't think that example works, all of the services are stubs that does not do anything.

Your template of microservices seems most comprehensive so you may have a good reason to skip API gateway?

Thanks.

**Comment by jglodek** [comment]
Hi, the infrastructure issues we're not taken in account here so:

We specifically didn't wrote single gateway authed  proxy for the project as it would mean a tightly coupled service and a somewhat single point of failure. 

Obviously a good infrastructure would make internal services hidden from public in a DMZ  either with VPN or some Internal API keys. 

Proper "fat" setup would also probably include smart load balancers for rolling deployment, maybe some reverse proxy caches and un-SSL-ing  proxies. All probably leveraging some a configuration management solution. Of course AWS does most of those things.

**Comment by luksow** [comment]
@Ciantic @jglodek's comment is very accurate. We skipped API gateway for clarity and ease of running this activator template. In a production environment it's **very** likely that you want an API gateway (ex. for load balancing or covering internal API). Here's a schema of very much the same system with an API gateway: http://www.slideshare.net/luksow/microservices-101-opportunities-dilemmas-and-problems#7

If that resolves your doubt, please close this issue. Also, should you have any more specific questions, please contact me via mail (can be found on my GH profile) - we can schedule a quick Skype call or something.

**Comment by Ciantic** [comment]
Thanks.

I have not found a single template with API gateway, there is no best practices yet. There are some problems that one needs to solve when implementing it. It would be interesting to see this template with API gateway, because it's probably required in real world applications.

Few questions raises to me immediately:

What is a good way to "redirect" a REST action to microservice? For example I might have "user service" with Controllers for registering, changing password etc. What would be a good way to redirect the request from API gateway to user service? In my mind the microservices should also be capable as standalone applications, that is they could serve the REST themselves if there is no API gateway.

How in reality you do the authentication and issuing a application specific JWT in the API Gateway?

I actually don't expect you people to answer or implement these, but I'm just putting these here. For example I don't think Play Framework is yet written to support splitting to microservice, the idea is still quiet a new one.

**Comment by jglodek** [comment]
Ad. API Gateway: 
with API gateway I meant nginx load balancers and such http://www.infoq.com/articles/seven-uservices-antipatterns suggests. 
— for internal API : I think it's not required given you should use configuration management, and that can easily perform all the load-balancing, without being single point of failure(maybe even distributed configuration-management which would be even safer). There are lot of strategies on handling configuration change event. 
— Public facing API could be load-balanced with elastic loadbalancer etc., given the load is big enough. You can do this in million ways, and there are ways of doing this without using a proxy-like a gateway, like DNS or frontend-side loadbalancing.

Ad. redirects:
There is a limited sense of doing redirects in an API. It makes sense for Web 1.0 Php, Rails, HTML views etc.; not exactly useful for API. Of course one of your user (or any actor) facing app can be written in Rails(given it makes a sense(ex. small load req + ruby productivity)) and there is no problem of doing redirects there.

Ad. JWT: You mean like 
POST /token/generate 
#=> {app_id:..., public_key:..., app_secret:..., valid_to:...}?

**Comment by luksow** [comment]
@Ciantic our microservices are standalone REST services. You could skip API gateway and call them directly. Ex. `my.microservices.com:8000` would lead to `auth-fb` so you can call it like ``my.microservices.com:8000/register/fb` or `my.microservices.com:8000/login/fb`. It's the same for other services.

Example nginx conf to create API gateway:

```
worker_processes  32;

events {
  worker_connections  4096;
}


http {
  include       mime.types;
  default_type  application/octet-stream;

  log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    '$status $body_bytes_sent "$http_referer" '
    '"$http_user_agent" "$http_x_forwarded_for"';

  sendfile        on;

  keepalive_timeout  65;

  server {
    listen       80;
    server_name  localhost;

    location ^~ /login {
      include /usr/local/openresty/nginx/conf/cors;

      add_header 'Access-Control-Allow-Origin' "$http_origin";
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_pass http://127.0.0.1:8001;
    }

    location ^~ /session {
      include /usr/local/openresty/nginx/conf/cors;

      add_header 'Access-Control-Allow-Origin' "$http_origin";
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_pass http://127.0.0.1:8002;
    }

    location ^~ /btc {
      include /usr/local/openresty/nginx/conf/cors;

      add_header 'Access-Control-Allow-Origin' "$http_origin";
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_pass http://127.0.0.1:8003;
    }
  }
}
```

**Comment by Ciantic** [comment]
I think the API gateway needs to be a own Play Framework application, that e.g. defines the routes and handles authentication like visioned here: http://nordicapis.com/how-to-control-user-identity-within-microservices/  by Jacob Ideskog (video: https://www.youtube.com/watch?v=BdKmZ7mPNns ). 

It's a long one but the gist of it is that you must have a API gateway which takes from a user it's ID reference, and then gets corresponding identity JWT and passes it to microservices.

Redirects was a bad term, I only meant same thing as in above nginx example but with Play, e.g.

(Pseudo code route file)

```
GET,POST   /user/*                     SomehowPassTheseToUserMicroservice
GET,POST   /billing/*                     SomehowPassTheseToBillingMicroservice
```

Then I could have in user service a clean route file such as 

```
POST   /signUp                     AuthController.signUp
GET    /loginSocial/:provider      AuthController.loginSocial(provider)
POST   /loginSocial/:provider     AuthController.loginSocial(provider)
...
```

but when accessed from API gateway the URL's would be "/user/signUp", ... prefixed with "user"

**Comment by luksow** [comment]
I have not considered such architecture. The problem with it is that by putting an gateway like this in front of all your microservices you're having a single point of failure. In my opinion the gateway should be as dumb as possible, hence proposition of nginx. With solutions like HAProxy or nginx you can still handle JWT or whatever suits you.
